server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web_service?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 3350
    driver-class-name: com.mysql.jdbc.Driver

#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true